### ISSUE TITLE
Wykrywać odlaczenie robota podczas dzialania ros2 control stack

### ISSUE THREAD

**Issue by twiniars** [GroupOfRobots/magician_ros2#16]
Można to robić na rożne sposoby. Po wykryciu odłączenia/utraty komunikacji zmienić stan sterownika na zablokowany. Wymusi to jego restart.

**Comment by yRagax** [comment]
Po zmianach w bringupie w końcu udało się to zaimplementować. Po odłączeniu USB wszystkie procesy zakończyły się sukcesem i wyłączyły się. Zdecydowałem, że użytkownik odzyskuje kontrolę w terminalu, i jest w stanie ponownie odpalić bringupa.

[odlaczanie_usb.mp4](https://github.com/user-attachments/assets/9d098a6f-b5fc-473a-9619-093123d2b93c)
