### ISSUE TITLE
Problem ze sterowaniem z GUI Janka - ruch serwa wokół osi pionowej

### ISSUE THREAD

**Issue by twiniars** [GroupOfRobots/magician_ros2#17]
Problem jest następujący. Zadając ruch serwa (ostatnia oś) ruch ten wykonuje się dłużej niż wciska się przycisk zlecający ten ruch. I teraz jeśli podczas tego ruchu (zanim faktycznie się zakończy), chce się poruszyć inną osią, to występują różne efekty, typu zatrzymanie ruchu w ostatniej osi, dziwna prędkość ruchu w innych osiach.

**Comment by yRagax** [comment]
Naprawione w taki sposób, że teraz po wciśnięciu przycisku, każdy inny jest deaktywowany. Następnie to odpuszczeniu przycisku, każdy inny aktywuje się z opóźnieniem 500ms, dzięki czemu nie można już spamować przyciskami.

https://github.com/user-attachments/assets/aa54fa10-0fa9-42f3-aa23-c9f1fd650966

**Comment by twiniars** [comment]
spróbuj zaimplementować deaktywowanie przycisków nie na określony  czas, ale do momentu zakończenia ruchu

**Comment by yRagax** [comment]
Poprawione, przetestowane.
```python 
if self.button_released:
    differences = [abs(current_joint_states[i] - self.previous_joint_states[i]) for i in range(len(current_joint_states))]
    if all(diff < self.joint_stability_threshold for diff in differences):
        self.button_released = False
        self.enable_buttons()
```
